// trending-configs.js — 系统推荐配置（当前最火题材）
// 这些配置会展示在 Dashboard 上，用户一键应用

const TRENDING_CONFIGS = [
  {
    id: 'trending-ba-zong',
    title: '🔥 霸总甜宠',
    badge: '日榜第一',
    badgeColor: '#e84142',
    description: '霸道总裁 × 灰姑娘 — 目前最火的短剧题材，完播率最高',
    tags: ['霸总', '甜宠', '先婚后爱', '豪门秘事'],
    config: {
      genre: '霸总',
      mood: '甜宠',
      style: '原生真人风',
      duration: 60,
      platform: 'douyin',
      characters: [
        { name: '厉夜霆', role: '霸道总裁', personality: '冷峻专横，内心温柔', voiceType: '深沉' },
        { name: '苏晚晚', role: '灰姑娘', personality: '温柔坚韧，善良倔强', voiceType: '甜美' },
      ],
      plotPoints: [
        '总裁被迫与灰姑娘契约结婚',
        '女主被公司同事排挤，男主暗中保护',
        '两人在朝夕相处中渐生情愫',
        '误会爆发，女主离家出走',
        '男主追妻火葬场，高甜结局',
      ],
    },
    publishPlaforms: ['douyin', 'kuaishou', 'bilibili'],
  },
  {
    id: 'trending-zhui-xu',
    title: '🔥 赘婿逆袭',
    badge: '热榜推荐',
    badgeColor: '#f59e0b',
    description: '赘婿身份 × 龙王归来 — 爽点密集，男性用户最爱',
    tags: ['赘婿', '逆袭', '打脸', '龙王'],
    config: {
      genre: '赘婿',
      mood: '逆袭',
      style: '原生真人风',
      duration: 120,
      platform: 'douyin',
      characters: [
        { name: '叶无双', role: '赘婿/龙王', personality: '隐忍低调，实力碾压', voiceType: '深沉' },
        { name: '沈清雪', role: '妻子', personality: '温柔善良，逐渐理解丈夫', voiceType: '甜美' },
      ],
      plotPoints: [
        '龙王叶无双隐姓埋名当赘婿',
        '岳母一家百般刁难',
        '妻子沈清雪暗中维护',
        '家族危机，叶无双展露实力',
        '龙王身份曝光，众人跪服',
      ],
    },
    publishPlaforms: ['douyin', 'kuaishou', 'weixin'],
  },
  {
    id: 'trending-chuan-yue',
    title: '🔥 穿越古风',
    badge: '新星推荐',
    badgeColor: '#7c3aed',
    description: '现代女主穿越古代 × 王爷太子 — 女性用户留存率最高的题材',
    tags: ['穿越', '古风', '宫斗', '甜虐'],
    config: {
      genre: '穿越',
      mood: '古风',
      style: '二次元动漫',
      duration: 60,
      platform: 'bilibili',
      characters: [
        { name: '顾清歌', role: '穿越女主/神医', personality: '古灵精怪，医术高明', voiceType: '甜美' },
        { name: '萧景琰', role: '战神王爷', personality: '冷面傲娇，嘴硬心软', voiceType: '深沉' },
      ],
      plotPoints: [
        '现代女医生穿越成将军府废柴小姐',
        '意外救了重伤的战神王爷',
        '两人被迫联手应对宫廷权谋',
        '男主不知不觉沦陷',
        '女主身份暴露，面临抉择',
      ],
    },
    publishPlaforms: ['bilibili', 'douyin', 'youtube'],
  },
  {
    id: 'trending-shen-xian',
    title: '🔥 修仙甜宠',
    badge: '潜力爆款',
    badgeColor: '#10b981',
    description: '修仙 × 甜宠 — 全年龄段通吃，海外市场表现优异',
    tags: ['修仙', '甜宠', '仙侠', '虐恋'],
    config: {
      genre: '修仙',
      mood: '甜宠',
      style: '水墨国风',
      duration: 120,
      platform: 'tiktok',
      characters: [
        { name: '云梦瑶', role: '修仙天才少女', personality: '活泼灵动，天赋异禀', voiceType: '甜美' },
        { name: '九天尊', role: '上界尊者转世', personality: '高冷强大，暗中守护', voiceType: '深沉' },
      ],
      plotPoints: [
        '废柴少女意外觉醒太古血脉',
        '神秘尊者暗中出手相助',
        '宗门大比上一鸣惊人',
        '身份被揭穿，遭遇追杀',
        '尊者挡在身前：谁敢动她？',
      ],
    },
    publishPlaforms: ['tiktok', 'youtube', 'instagram'],
  },
  {
    id: 'trending-shi-hao',
    title: '🔥 都市悬疑',
    badge: '海外热门',
    badgeColor: '#4a6cf7',
    description: '悬疑 × 都市 — TikTok 海外数据最好的国产短剧类型',
    tags: ['悬疑', '都市', '反转', '短剧出海'],
    config: {
      genre: '悬疑',
      mood: '反转',
      style: '原生真人风',
      duration: 60,
      platform: 'tiktok',
      characters: [
        { name: '林深', role: '刑警队长', personality: '冷静果断，直觉超群', voiceType: '深沉' },
        { name: '顾小雨', role: '犯罪心理师', personality: '聪明细腻，洞察力强', voiceType: '温暖' },
      ],
      plotPoints: [
        '离奇命案发生，所有证据指向一个已死之人',
        '刑警与心理师联手调查',
        '每个证人都有不在场证明',
        '真相比想象中更残酷',
        '最后的反转让所有人震惊',
      ],
    },
    publishPlaforms: ['tiktok', 'youtube', 'instagram', 'facebook'],
  },
  {
    id: 'trending-ba-zong-02',
    title: '🔥 霸总追妻',
    badge: '持续爆火',
    badgeColor: '#e84142',
    description: '追妻火葬场 × 双胞胎替身 — 女频S级爆款公式',
    tags: ['霸总', '追妻', '双胞胎', '虐心'],
    config: {
      genre: '霸总',
      mood: '甜宠',
      style: '原生真人风',
      duration: 120,
      platform: 'douyin',
      characters: [
        { name: '陆寒霆', role: '霸道总裁', personality: '冷酷无情，追妻时卑微', voiceType: '深沉' },
        { name: '温如意', role: '替身女主', personality: '隐忍坚韧，离开后光芒万丈', voiceType: '甜美' },
      ],
      plotPoints: [
        '女主当了三年白月光替身',
        '男主从未正眼看过她',
        '女主心死离开，华丽蜕变',
        '男主发现真相崩溃',
        '追妻火葬场：跪求原谅',
      ],
    },
    publishPlaforms: ['douyin', 'kuaishou', 'weixin'],
  },
];

export default TRENDING_CONFIGS;
